### ISSUE TITLE
[Error]: Cannot find module './rules/best-practices'

### ISSUE THREAD

**Issue by rockchalkwushock** [EQuimper/eslint-config-equimper#1]
I am receiving the following error message:

```plaintext
Error: Cannot read config file: /Users/codybrunner/Desktop/photography-frontend/node_modules/eslint-config-equimper/index.js Error: Cannot find module './rules/best-practices' Referenced from: /Users/codybrunner/Desktop/photography-frontend/.eslintrc
Error: Cannot read config file: /Users/codybrunner/Desktop/photography-frontend/node_modules/eslint-config-equimper/index.js
Error: Cannot find module './rules/best-practices'
Referenced from: /Users/codybrunner/Desktop/photography-frontend/.eslintrc
    at Function.Module._resolveFilename (module.js:455:15)
    at resolve (internal/module.js:27:19)
    at Array.map (native)
    at Object.<anonymous> (/Users/codybrunner/Desktop/photography-frontend/node_modules/eslint-config-equimper/index.js:13:5)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
```

As I'm understanding it looking at the _index.js_ to the module by accessing `"extends": "equimper"` I am basically getting the eslint config from _index.js_. The error message is showing that the `.map()` is failing at the _./rules/best-practices_. I'm not quite sure what the `require.reslolve` is doing so I can't deduce much more from this point.

Is `eslint` & `babel-eslint` required as _dev-deps_ in the project directory? I would think not since they are built into your package as dependencies. I have tried _removing_ & _adding_ again, but still get this error. I'm also wondering if the _.eslintrc_ needs to be set up with more than just the `"extends"` property.

Below are my `.eslintrc` & `package.json`:

_.eslintrc_
```json
{
  "extends": "equimper"
}
```

_package.json_
```json
  "dependencies": {
    "next": "^2.0.0-beta",
    "react": "^15.4.2"
  },
  "devDependencies": {
    "eslint-config-equimper": "^1.0.8"
  }
```

 A link to the repository I'm using your package in can be found [here](https://github.com/rockchalkwushock/photography-frontend/tree/beta).

**Comment by EQuimper** [comment]
Thank this is fixed in version 1.1.0
